let ctx,osc,oscGain,delay,feedback,master,stream,recorder,lastBlob,lastBuffer;const decks={A:{buffer:null,source:null,reversed:false},B:{buffer:null,source:null,reversed:false}};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
async function init(){if(ctx){await ctx.resume();return}ctx=new (window.AudioContext||window.webkitAudioContext)();osc=ctx.createOscillator();oscGain=ctx.createGain();delay=ctx.createDelay(2);feedback=ctx.createGain();master=ctx.createGain();osc.type="sine";osc.frequency.value=220;oscGain.gain.value=.3;delay.delayTime.value=.24;feedback.gain.value=.18;osc.connect(oscGain);oscGain.connect(master);master.connect(ctx.destination);master.connect(delay);delay.connect(ctx.destination);delay.connect(feedback);feedback.connect(delay);osc.start();$("#power").textContent="AUDIO ON";$("#power").classList.add("on")}
$("#power").onclick=init;
$$("[data-wave]").forEach(b=>b.onclick=async()=>{await init();$$("[data-wave]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");osc.type=b.dataset.wave});
function range(id,out,fn){$(id).oninput=e=>{let v=+e.target.value;$(out).value=v+(id==="#freq"?" Hz":"%");if(ctx)fn(v)}}
range("#freq","#freqOut",v=>osc.frequency.setTargetAtTime(v,ctx.currentTime,.02));range("#oscLevel","#oscLevelOut",v=>oscGain.gain.setTargetAtTime(v/100,ctx.currentTime,.02));range("#echo","#echoOut",v=>delay.delayTime.setTargetAtTime(.05+v/100*.75,ctx.currentTime,.02));range("#feedback","#feedbackOut",v=>feedback.gain.setTargetAtTime(v/100,ctx.currentTime,.02));
$("#record").onclick=async()=>{await init();try{stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);let chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=async()=>{lastBlob=new Blob(chunks,{type:recorder.mimeType});lastBuffer=await ctx.decodeAudioData(await lastBlob.arrayBuffer());stream.getTracks().forEach(t=>t.stop());$("#micStatus").textContent="CAPTURED "+lastBuffer.duration.toFixed(1)+"s";$("#record").disabled=false;$("#stopRecord").disabled=true};recorder.start();$("#micStatus").textContent="RECORDING";$("#record").disabled=true;$("#stopRecord").disabled=false}catch(e){$("#micStatus").textContent="MIC BLOCKED"}};
$("#stopRecord").onclick=()=>recorder?.state==="recording"&&recorder.stop();
function copyBuffer(buf,reverse=false){const b=ctx.createBuffer(buf.numberOfChannels,buf.length,buf.sampleRate);for(let c=0;c<buf.numberOfChannels;c++){let a=buf.getChannelData(c),d=b.getChannelData(c);if(reverse){for(let i=0;i<a.length;i++)d[i]=a[a.length-1-i]}else d.set(a)}return b}
function stopDeck(n){let d=decks[n];try{d.source?.stop()}catch{}d.source=null;document.querySelector('[data-deck="'+n+'"].deck').classList.remove("playing")}
async function playDeck(n){await init();let d=decks[n];if(!d.buffer)return;stopDeck(n);let s=ctx.createBufferSource();s.buffer=d.buffer;s.playbackRate.value=+$("#speed"+n).value;s.connect(master);s.onended=()=>stopDeck(n);d.source=s;s.start();document.querySelector('[data-deck="'+n+'"].deck').classList.add("playing")}
$$("[data-action]").forEach(b=>b.onclick=async()=>{let n=b.dataset.deck,a=b.dataset.action,d=decks[n];if(a==="load"){await init();if(!lastBuffer)return;d.buffer=copyBuffer(lastBuffer);d.reversed=false;$("#counter"+n).textContent=d.buffer.duration.toFixed(1)+" SEC"}if(a==="play")playDeck(n);if(a==="stop")stopDeck(n);if(a==="reverse"&&d.buffer){stopDeck(n);d.buffer=copyBuffer(d.buffer,true);d.reversed=!d.reversed;$("#counter"+n).textContent=(d.reversed?"REV · ":"")+d.buffer.duration.toFixed(1)+" SEC"}});